name: Pipeline-CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: New folder

    steps:

      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Check Azure secrets
      - name: Check Azure Secrets
        shell: bash
        env:
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          if [ -n "$CLIENT_ID" ]; then
            echo "CLIENT ID = EXISTS"
          else
            echo "CLIENT ID = EMPTY"
          fi

          if [ -n "$TENANT_ID" ]; then
            echo "TENANT ID = EXISTS"
          else
            echo "TENANT ID = EMPTY"
          fi

          if [ -n "$SUBSCRIPTION_ID" ]; then
            echo "SUBSCRIPTION ID = EXISTS"
          else
            echo "SUBSCRIPTION ID = EMPTY"
          fi

      # 3. Azure login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 4. Verify Azure login
      - name: Verify Azure Login
        run: az account show

      # 5. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 6. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 7. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check

      # 8. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 9. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="location=Canada Central"
